server:
  port: 8081

# Microsserviço de busca de endereço por CEP
ms:
  client:
    address:
      url: http://localhost:8082/addresses

# Configuração do MongoDB
spring:
  data:
    mongodb:
      host: localhost
      port: 27017
      authentication-database: admin
      username: root
      password: example
      database: hexagonal

# Mongo Express
mongo:
    image: mongo-express
    restart: always
    ports:
        - 8083:8083
    environment:
        ME_CONFIG_MONGODB_ADMINUSERNAME: root
        ME_CONFIG_MONGODB_ADMINPASSWORD: example
        ME_CONFIG_MONGODB_URL: mongodb://root:example@mongo:27017/